name: Python CI  
  
on:  
  schedule:  
    - cron: '0 */4 * * *' # 每2小时运行一次  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      - name: Set up Python 3.9 
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.9
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install requests
      - name: Run Python script  
        run: |  
          python find_gd_iptv.py
