# run find_gd_iptv.py
name: Auto ETL IPTV
on:  
  schedule:  
    - cron: '0 */4 * * *' # 每2小时运行一次  
  workflow_dispatch:
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      - name: Set up Python 3.9 
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.9
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install requests
      - name: Run Python script  
        run: |  
          python find_gd_iptv.py
          cat mytv.m3u8
      - name: Push
        run: |
            git config user.name Watercolor-tone
            git config user.email Watercolor-tone@github.com
            git add .
            git commit -m "update"
            git push
